routes/main.py
import os
from pathlib import Path
from flask import Blueprint, render_template, request, flash, session, url_for, redirect
from werkzeug.utils import secure_filename
from extensions import current_year
from operations.messenger import send_email
from operations.miscellaneous import generate_captcha, text_match
from datetime import datetime


main = Blueprint('main', __name__, static_folder='static', template_folder='templates')


@main.route('/', methods=['GET', 'POST'])
def home():
    full_img_path = 'static/images/concepts/Coven/full/'
    thumbnail_img_path = 'static/images/concepts/Coven/thumbnail/'
    full_img_list = os.listdir(full_img_path)
    thumbnail_img_list = os.listdir(thumbnail_img_path)

    dict_1 = {}
    img_list_1 = ['selected 3 thumbnails', 'thumbnails exploration', 'developed final thumbnail']
    index_1 = 1

    dict_2 = {}
    img_list_2 = ['tower', 'tower silhouettes', 'tower developed thumbnails', 'tower concept', 'cart', 'cart wireframe',
                  'broom drawing', 'witch broom jet propelled', 'sculptures potions concept']
    index_2 = 1

# searches and finds exact filename in full and thumbnail folder and prepares dict entry
    for img in img_list_1:
        full_img = text_match(img, full_img_list)[0]
        full_img_file_path = full_img_path + full_img
        thumbnail = text_match(img, thumbnail_img_list)[0]
        thumbnail_file_path = thumbnail_img_path + thumbnail
        title = Path(full_img).stem[:-2].replace('_', ' ')
        img = {
            'title': title,
            'thumbnail': '../' + thumbnail_file_path,
            'full': '../' + full_img_file_path
        }
        dict_1[index_1] = img
        index_1 += 1

    for img in img_list_2:
        full_img = text_match(img, full_img_list)[0]
        full_img_file_path = full_img_path + full_img
        thumbnail = text_match(img, thumbnail_img_list)[0]
        thumbnail_file_path = thumbnail_img_path + thumbnail
        title = Path(full_img).stem[:-2].replace('_', ' ')
        img = {
            'title': title,
            'thumbnail': '../' + thumbnail_file_path,
            'full': '../' + full_img_file_path
        }
        dict_2[index_2] = img
        index_2 += 1



    return render_template('index.html', current_year=current_year, dict_1=dict_1, dict_2=dict_2)


@main.route('/concept_artworks', methods=['GET', 'POST'])
def concept_artworks():
    project = request.args.get('project')
    artworks_dir = 'static/images/concepts/' + project + '/'
    artwork_list = os.listdir(artworks_dir)
    artwork_url_list = []
    for artwork in artwork_list:
        if artwork != 'Hero.jpg':
            artwork_url = 'static/images/concepts/' + project + '/' + artwork
            artwork_url_list.append(artwork_url)
    artwork_url_list.sort()
    return render_template('concept_artworks.html', project=project, artwork_url_list=artwork_url_list,
                           current_year=current_year)



@main.route('/contact', methods=['GET', 'POST'])
def contact():
    captcha_value, captcha_uri = generate_captcha()
    session['captcha_value'] = captcha_value
    session['url'] = request.url

    return render_template('contact.html', captcha=captcha_uri, captcha_value=captcha_value)


@main.route('/captcha_verification', methods=['GET', 'POST'])
def captcha_verification():
    if request.method == 'POST':
        captcha_value = session.get('captcha_value')
        if request.form.get('captcha') != captcha_value:
            spam_report = f'{datetime.now()} -- Captcha Fail -- \n'
            with open('spam_report.txt', 'a') as f:
                f.write(spam_report)
            flash("Wrong Captcha!", "error")
        else:
            name = request.form.get('name')
            email = request.form.get('email')
            email2 = request.form.get('email2')
            msg = request.form.get('message')
            if email == email2:
                message = f'{msg}\n\n\nSENDER DETAILS:\nName: {name}\nEmail: {email}\n'

                success_msg = (f'Dear {name},\n\nThanks for sending me a message.\nI will get back to you as soon as possible. '
                           f':)\n\n\nShwetabh Suman\nConcept Artist & Illustrator\nNew Delhi, India')
                send_email('IMPORTANT!! - Main Portfolio', ['shwetabhartist@gmail.com'], email, message, '', '')
                send_email('MESSAGE SENT - Shwetabh Suman', [email], 'shwetabhartist@gmail.com', success_msg, '', '')
                flash('Message sent successfully!', 'success')
            else:
                flash("The email doesn't match!", "error")
    return redirect(session.get('url'))


@main.route('/temp', methods=['GET', 'POST'])
def temp():
    if request.method == 'POST':
        uploaded_file = request.files['file']
        if uploaded_file.filename != '':
            uploaded_file.save('static/'+uploaded_file.filename)
        flash('File uploaded successfully', 'success')
    return render_template('temp.html')

routes/templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Shwetabh Suman</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css')}}"
    />
<!--    <link rel="shortcut icon" href="{{ url_for('static', filename='Logo_promotion_writart_tiny.ico') }}">-->

    {% block style %}
    {% endblock %}

  </head>

  <body>

  <header>
    <div id="brand"><a href="/">SHWETABH SUMAN</a></div>
    <nav>
      <ul>
        <li><a href="{{ url_for('main.contact') }}">Contact</a></li>
      </ul>
    </nav>
    <div id="hamburger-icon" onclick="toggleMobileMenu(this)">
      <div class="bar1"></div>
      <div class="bar2"></div>
      <div class="bar3"></div>
      <ul class="mobile-menu">
        <li><a href="{{ url_for('main.contact') }}">Contact</a></li>
      </ul>
    </div>
  </header>

  {% block content %}
  {% endblock %}

  <div id="footer">
      <div id="copyright">
        <p>&#169 {{ current_year }} | illustrations.shwetabhsuman.com | All rights reserved | Any sort of infringement may attract legal consequences.</p>
      </div>
  </div>
  </body>
  <script src="{{ url_for('static', filename='js/base.js')}}"></script>
</html>

routes/templates/concept_artworks.html
{% extends "base.html" %}
{% block content %}


{% endblock %}

routes/templates/contact.html
{% extends "base.html" %}
{% block content %}
<style>
    #contact-bg {
        background: url(static/images/contact/cover.jpg) center center no-repeat;
        background-size: cover;
    }
    #contact-bg form {
        background: rgba(0, 0, 0, 0.5);
        padding: 2% 5% 5% 5%;
    }
    #captcha {
        display:flex;
        width:100%;
        padding-bottom:1%;
        justify-content: space-between;
    }
    #captcha div {
        width: 50%;
    }
    #captcha_input {
        width:48%;
    }

</style>
<div style="width:100%;">
    <div class="full-page-form-container form-main" id="contact-bg">
        <form action="{{ url_for('main.captcha_verification') }}" method="post" id="contact-form">
            <p class="heading-large white-color text-center">DROP A MESSAGE</p>
            <input type="text" name="name" placeholder="Name" required>
            <input type="email" name="email" placeholder="Email" required>
            <input type="email" name="email2" placeholder="Please Retype Email"required>
            <textarea name="message" placeholder="Message" required></textarea>
            <div id="captcha">
                <div style="display:flex; justify-content:center;"><img src="{{captcha}}" width="350" height="50"></div>
                <input id="captcha_input" type="text" name="captcha" placeholder="Enter Captcha" required>
            </div>
            <button class="btn-1" type="submit">SEND MESSAGE</button>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                  <div class="{{category}}" style="background:black;">{{ message }}</div>
                {% endfor %}
            {% endif %}
            {% endwith %}
        </form>
        <a class="btn-1 whatsapp text-center" href="https://wa.link/qyhvtj" target="_blank">CHAT ON WHATSAPP</a>
    </div>
</div>


{% endblock %}

routes/templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
    .artworks-container {
        display:flex;
        flex-direction: column;
        flex-wrap: wrap;
        padding: 2% 5%;
        background: black;
        text-align: center;
        color: gray;
        width: 100%;
    }

    .artworks img {
        max-height: 300px;
        max-width: 100%;
        object-fit: cover;
        margin: 1%;
    }
    .artworks-container h3{
        font-size: 2.2rem;
    }
    .artworks-container p {
        font-size: 1.2rem;
        padding-bottom: 0%;
        margin-bottom: 0%;
    }
#full-size-img-box {
    display:flex;
    flex-direction:column;
    justify-content:center;
    align-items:center;
    background: white;
}
#full-size-img-box img {
    max-height:80vh;
    max-width:100vw;
}
#full-size-img-box h3 {
    font-size:1.5rem;
}
.artwork-popup {
    position: fixed;
    top:50%;
    left:50%;
    transform: translate(-50%, -50%);
}
#artwork-popup {
    display:none;
}
.artwork-popup {
    z-index: 100;
}
#artwork-popup-overlay {
    display: none; /* Hidden by default */
    position: fixed; /* Cover the whole viewport */
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.7); /* Semi-transparent black */
    z-index: 1; /* Ensure it's behind the popup */
}
.artwork-popup p, .artwork-popup a {
    font-size: 1rem;
}

.cover-img-container {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    background: black;
    width: 100%;
}
.cover-img-container img{
    object-fit: cover;
    max-height: 80vh;
    max-width: 70%;
}

@media only screen and (min-width : 1900px) {

}
@media only screen and (max-width : 1900px) {
    .artworks-container h3{
        font-size: 1.8rem;
    }
    .artworks-container p {
        font-size: 1rem;
    }
    .artworks img {
        max-height: 230px;
    }
}
.artwork-popup p, .artwork-popup a {
    font-size: 1rem;
}
@media only screen and (max-width : 1440px) {
    .artworks img {
        max-height: 170px;
    }
    .artworks-container h3{
        font-size: 1.6rem;
    }
    .artworks-container p {
        font-size: 0.9rem;
    }

#full-size-img-box h3 {
    font-size:1.3rem;
}
}
@media only screen and (max-width : 1024px) {
    .artworks-container h3{
        font-size: 1.4rem;
    }
#artwork-popup {
    padding-bottom:2%;
}
 .artworks img {
        height: 128px;
    }
    .artworks-container p {
        font-size: 0.8rem;
    }
#full-size-img-box h3 {
    font-size:1.2rem;
}
}
@media only screen and (max-width : 768px) {
     .artworks img {
        height: 120px;
    }
    .artworks-container h3{
        font-size: 1.3rem;
    }
    .artwork-popup p, .artwork-popup a {
        font-size: 0.8rem;
    }
#full-size-img-box h3 {
    font-size:1.1rem;
}
}
@media only screen and (max-width : 576px) {
    .artworks img {
        height: 100px;
    }
    .artworks-container h3{
        font-size: 1.2rem;
        padding-top:4%;
    }
    .artwork-popup p, .artwork-popup a {
        font-size: 0.7rem;
    }
#full-size-img-box h3 {
    font-size:1rem;
}
}
</style>
<div style="background: black;">
    <div class="artworks-container">
        <h3>COVEN - Concept & Design</h3>
    </div>
    <div class="cover-img-container">
        <img src="../static/images/concepts/Coven/full/Colored_Render-f.jpg" loading="lazy">
    </div>
    <div class="artworks-container">
        <P>Please click small images to view in large size.</P>
        <div class="artworks">
        {% for img in dict_1 %}
        <a type="button" onclick="openFullImage('{{dict_1[img]['full']}}', '{{dict_1[img]['title']}}')"><img src="{{dict_1[img]['thumbnail']}}"></a>
        {% endfor %}
        </div>
    </div>
    <div class="cover-img-container">
        <img src="../static/images/concepts/Coven/full/Level_Basic_Layout-f.jpg" loading="lazy">
        <p style="color:#BFBFBF;">Level Basic Layout</p>
    </div>
    <div class="artworks-container">
        <P>Please click small images to view in large size.</P>
        <div class="artworks">
        {% for img in dict_2 %}
        <a type="button" onclick="openFullImage('{{dict_2[img]['full']}}', '{{dict_2[img]['title']}}')"><img src="{{dict_2[img]['thumbnail']}}"></a>
        {% endfor %}
        </div>
    </div>

<!-- Image full size zoom popup -->
    <div id="artwork-popup-overlay" onclick="closeFullImage()"></div>
    <div class="artwork-popup">
        <div id="artwork-popup">
            <div style="display:flex; justify-content:space-between; width:100%; background:black; color:gray; padding:1% 2% 0% 2%;">
                <p>IMAGE VIEWER</p>
                <a type="button" style="color:white;" onclick="closeFullImage()">Close</a>
            </div>
            <div id="full-size-img-box">
                <h3 id="artwork-title"></h3>
                <img id="full-size-img" src="">
            </div>
        </div>
    </div>
</div>
<script src="/static/js/portfolio.js"></script>
{% endblock %}

routes/templates/temp.html
{% extends "base.html" %}
{% block content %}
<style>
        #Progress_Status {
          width: 100%;
          background-color: #ddd;
          display: none;
        }
        #myprogressBar {
          width: 2%;
          height: 20px;
          background-color: #4CAF50;
        }
        </style>
<div class="full-page-form-container">
    <form id="upload-form" method="post" action="{{url_for('main.temp')}}" enctype="multipart/form-data">
        <p class="heading-medium">Upload blender file here </p>
        <p><input type="file" name="file" required></p>
        <p><button class="btn-1" onclick="update()" style="background:#E07A31;color:white;" type="submit">UPLOAD</button></p>
        <div id="Progress_Status">
            <div id="myprogressBar"></div>
        </div>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                  {% for category, message in messages %}
                    <div class="{{category}}">{{ message }}</div>
                  {% endfor %}
            {% endif %}
        {% endwith %}
    </form>

</div>


<script>
        function update() {
            var element = document.getElementById("myprogressBar");
            var progress = document.getElementById("Progress_Status");
            progress.style.display = "block";
            var width = 1;
            var identity = setInterval(scene, 10);
            function scene() {
            if (width >= 100) {
                clearInterval(identity);
            } else {
                width++;
                element.style.width = width + '%';
                }
            }
        }
        </script>
{% endblock %}